### ISSUE TITLE
Could not find module in c9

### ISSUE THREAD

**Issue by duyngha** [Viet-Artisans/generator-vacore#8]
```bash
module.js:327
    throw err;
    ^

Error: Cannot find module '../vacore-base.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/generator-vacore/app/index.js:2:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

**Comment by duyngha** [comment]
because `generator-vacore` was missing the `vacore-base.js` file. Push it from repository by edit `package.json` file:
```bash
"files": [
"vacore-base.js"
]
```
